# Generated by Django 3.2 on 2021-10-05 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
    ]
